version: '{build}'

skip_commits:
  files:
    - '**/*.md'

image: Visual Studio 2019

init:
  - cmd: git config --global core.autocrlf false
  - ps: |
      $ErrorActionPreference = "Stop"
      $tagName = $env:APPVEYOR_REPO_TAG_NAME
      if ($tagName -match '^v\d+\.\d+') # tag name starts with 'vX.Y'
      {
        $env:SHOULD_PUBLISH_NUGET_PACKAGE = "true"
        Write-Host "Will publish nuget package for $tagName tag" -ForegroundColor "Green"
        if ($tagName -match '^v\d+\.\d+-release') # tag name starts with 'vX.Y-release' (e.g. use 'v4.2-release.1' tag for the first patch for release v4.2)
        {
          $env:SHOULD_CREATE_RELEASE = "true"
          Write-Host "Will create release for $tagName tag" -ForegroundColor "Green"
        }
      }

nuget:
  disable_publish_on_pr: true

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore ./Cassandra.ThriftClient.sln --verbosity minimal
  - cmd: dotnet tool restore

build_script:
  - cmd: dotnet build --configuration Release ./Cassandra.ThriftClient.sln
  - cmd: dotnet pack --no-build --configuration Release ./Cassandra.ThriftClient.sln

test_script:
  - cmd: dotnet jb cleanupcode Cassandra.ThriftClient.sln --profile=CatalogueCleanup --exclude=Cassandra.ThriftClient/Internal/**/*.cs --verbosity=WARN
  - cmd: git diff --exit-code
  - cmd: dotnet test --no-build --verbosity normal --configuration Release ./Cassandra.ThriftClient.Tests/Cassandra.ThriftClient.Tests.csproj

artifacts:
  - path: './Cassandra.ThriftClient/bin/Release/*.nupkg'

deploy:
  - provider: NuGet
    server: https://nuget.org
    api_key:
      secure: y2RPf+gBBqffQVm8pg9qZcg99m7K8hsSa4z7VHvIE6t+kuO7r/oIqTVcryZzL93D
    skip_symbols: true
    on:
      SHOULD_PUBLISH_NUGET_PACKAGE: true

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: y8dDOcAtq4U1MTDJFX8f23xsvyFU1u4bhwr9Lzbkf2revNWPPTifBkWghris9v8i
    draft: false
    prerelease: false
    on:
      SHOULD_CREATE_RELEASE: true
