version: "3.8"
services:
  cassandra:
    container_name: cassandra
    image: bitnami/cassandra:3.11
    environment:
      - CASSANDRA_START_RPC=true
      - JAVA_OPTS=-Xms2G -Xmx2G
    ports:
      - "9042:9042"
      - "9160:9160"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 10s
      retries: 60