/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Apache.Cassandra
{
  /// <summary>
  /// CQL query compression
  /// </summary>
  internal enum Compression
  {
    GZIP = 1,
    NONE = 2,
  }
}
