/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Apache.Cassandra
{

  /// <summary>
  /// Row returned from a CQL query.
  /// 
  /// This struct is used for both CQL2 and CQL3 queries.  For CQL2, the partition key
  /// is special-cased and is always returned.  For CQL3, it is not special cased;
  /// it will be included in the columns list if it was included in the SELECT and
  /// the key field is always null.
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CqlRow : TBase
  {

    public byte[] Key { get; set; }

    public List<Column> Columns { get; set; }

    public CqlRow() {
    }

    public CqlRow(byte[] key, List<Column> columns) : this() {
      this.Key = key;
      this.Columns = columns;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_key = false;
        bool isset_columns = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Key = iprot.ReadBinary();
                isset_key = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  Columns = new List<Column>();
                  TList _list82 = iprot.ReadListBegin();
                  for( int _i83 = 0; _i83 < _list82.Count; ++_i83)
                  {
                    Column _elem84;
                    _elem84 = new Column();
                    _elem84.Read(iprot);
                    Columns.Add(_elem84);
                  }
                  iprot.ReadListEnd();
                }
                isset_columns = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_key)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Key not set");
        if (!isset_columns)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Columns not set");
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("CqlRow");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Key == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Key not set");
        field.Name = "key";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Key);
        oprot.WriteFieldEnd();
        if (Columns == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Columns not set");
        field.Name = "columns";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Columns.Count));
          foreach (Column _iter85 in Columns)
          {
            _iter85.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("CqlRow(");
      __sb.Append(", Key: ");
      __sb.Append(Key);
      __sb.Append(", Columns: ");
      __sb.Append(Columns);
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
